### ISSUE TITLE
Pin Rust toolchain version?

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/signal-protocol#11]
Shall we add a [`rust-toolchain`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file to set the default toolchain in this project to either `nightly`, or follow the libsignal-client upstream pinned nightly version [here](https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust-toolchain#)?

**Comment by redshiftzero** [comment]
I say for now let's pin to a specific version (what upstream is using works) for build determinism

**Comment by pierwill** [comment]
Sounds good. 👍 

I did notice that the build script here is using `stable`: https://github.com/freedomofpress/signal-protocol/blob/c9be8bdf63d9c0780161cba4bd9c323b97662b87/build-wheels.sh#L4. Should this stay the same?

**Comment by redshiftzero** [comment]
ah that would need to change along with these two places in CI: https://github.com/freedomofpress/signal-protocol/blob/main/.circleci/config.yml#L30 and https://github.com/freedomofpress/signal-protocol/blob/main/.circleci/config.yml#L11
